language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: "__token__"
  password:
    secure: BWLMyhVo/+Wk8wH0A29JjWW46PJrheX+0mzz8dKUbExptAOx052kZqgl0svIZs/qRmhFeLuh+95+JwlIkdjRuyHCWSppUmBweViSQwM+BdK8cOgjUn6eTVp26ymiQbuFTehuC8Cncj/ExD2xvysrJRxtLKNI+bQ+RBkgYrSGOnpxV+S6bVaZQ00NRSQFT4MmeQkRX5msir3ZYRXoTCJTGVq1ZvTVI7nAmo8DOVLtXDl8VjbdItmKhIcOEWLgZg2RfbG4paW4ebZ2XVKeFM/5z+2UkOJoRSVZWzgzi1lNhrvOZUHN6iMTgaKA5yxchjVku5DdmLcQjDIxsiOu/cakhGOxt83YN+jfAIr3AyfMN01coOFrsCQmiR0wkJDuTDEN1F8L88hwkHrPqdEpObSGEIEfZVhFJMiz7LqYGXlUR82xZIM4IPpjsAonL9gXdUQ0ciWarvUdIgHpCh9PudjqsQMgjXwSQblB/euD45ygQkqq8FvtFr3M1yVaAkoikAXflHVEBQAnOPTNPjM3aepIcaPZqlPfV6KDZ0CKDa+LbLz2FYOf+1iT+tvRIhlE7+blsPGkA8f5bhkRbFiz7kzHnZftq/YmQTGuDsknjxP0lCjCZupiEu02ePepcQ7Qtsvz3PT7DbMxMYMHQNM75RDajqD1ItgOYJzXRhDDmCCj3iE=
  on:
    tags: true
    repo: gpp-rnd/anchors
    python: 3.8
